### ISSUE TITLE
instaa problem

### ISSUE THREAD

**Issue by fipoucat** [CMCC-Foundation/Zapata#7]
I am trying to install Zapata using conda without success, It last hours without ending.

Any help

**Comment by Chony-B** [comment]
FYI: I faced a similar problem (Linux anyway - on the Mac eventually finished). 
My (linux) work around has just been not to use the virtual environment and to ensure all dependencies are installed. Also means I haven't locked to any particular versions of packages which may or may not be wise as I think that opens a whole new can of worms (some extra fun is fine with me).

**Comment by fipoucat** [comment]
Ok
